name: Build iOS Simulator App

on:
  workflow_dispatch: # Allows you to trigger this manually from GitHub

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.1"
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Make .env file
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          envkey_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

      - name: Run build_runner
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build iOS Simulator Bundle
        run: |
          # The --simulator flag ensures it builds a .app bundle, not a .ipa
          flutter build ios --simulator --no-codesign

      - name: Zip the .app bundle
        run: |
          cd build/ios/iphonesimulator
          zip -r ../../../Runner.app.zip Runner.app

      - name: Upload Artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: appetize-ios-bundle
          path: Runner.app.zip